version = 1

test_patterns = [
  "tests/**",
  "examples/**"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "shell"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "isort"